### PR TITLE
Completed New York Times Page Clone

### PR DESCRIPTION
**Pull request by ikraamg**
Live Preview Link: https://rawcdn.githack.com/DennisOsido/NY-Times-Clone/7d5d8ef0f89e4f97bc07942cd7d0142450c11a95/index.html

*EDIT after the first review:
-Added side section for editors pics
-Changed styles to better match original
-Made site more responsive using 1366 x 768px as a baseline*

In this project we:
-Created an HTML structure of the page and styled it with CSS Grid and Flexbox and Floats.

Steps:
-Created a Navbar
-Created a main section with the core content and images
-Created an article section.
-Created an aside section.
-Created a footer section.

Location of layout requirements that were completed:
Grid was used for the body excluding the navbar.
Flex was used for navbar and article sections among others.
Floats were used in the footer.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by ikraamg** [comment]
Hi @Oluwadamilareolusakin, the stickler took long to run, i see it finally ran now. I've also just updated the live preview in the pull request description. Can you please have a look to see if you are reviewing the correct version. Thanks!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great team effort @ikraamg and @DennisOsido 
Your page is coming together really nicely, I love your Readme file and your PR description. Please consider my comments below, make the necessary changes and request another review! :+1: 

#### Page Styling
Please take a look at the following screenshots I am attaching below, a few things you may notice here if you compare your project with the original, please take not of the width of various sections, paddings, text alignments and element alignments.

##### Footer
* Yours
screenshot
* Original
screenshot

##### Editor's Picks
This section is missing altogether, please look into it :handshake: 
* Original
screenshot

#### More in Space and Cosmos
* Yours
screenshot
* Original
screenshot

### Summary
Please consider my comments above,  make the changes to the styling and the request another review! Please keep in mind that I didn't point out every section that has an issue, please look through them all thoroughly so you don't need multiple reviews :+1: I wish you the best, and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by ikraamg** [comment]
After the first review:
-Added side section for editors pics
-Changed styles to better match original
-Made site more responsive using 1366*768px as a baseline

**Comment by nikasulo** [comment]
Nice work team!  :clap:, your review is in progress 😊

**Review by nikasulo — APPROVED** [review]
# Wonderful effort! @ikraamg and @DennisOsido 
You have done well and handled the changes nicely. You may merge and keep moving forward! :rocket: I wish you the best in your endeavours and see you at the very top! :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
